"""Add history_count to User model

Revision ID: 05e3eb43c5a9
Revises: a2d1826237ab
Create Date: 2024-11-11 10:52:42.389288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e3eb43c5a9'
down_revision = 'a2d1826237ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_count', sa.Integer(), nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('facility_name')
        batch_op.drop_column('country')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('clinical_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_position', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('facility_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('history_count')

    # ### end Alembic commands ###
