"""Add user profile fields

Revision ID: 92387ea94d1b
Revises: 05e3eb43c5a9
Create Date: 2024-11-11 11:40:07.615309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92387ea94d1b'
down_revision = '05e3eb43c5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('history_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
