"""Added missing fields to user profile

Revision ID: 9cfe2882478c
Revises: a0b9327eb149
Create Date: 2024-11-13 11:49:58.763116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfe2882478c'
down_revision = 'a0b9327eb149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facility_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=True))
        batch_op.drop_column('facility_name')
        batch_op.drop_column('clinical_position')
        batch_op.drop_column('years_of_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_of_experience', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('clinical_position', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('facility_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('contact_number')
        batch_op.drop_column('facility_address')
        batch_op.drop_column('title')
        batch_op.drop_column('hospital_name')

    # ### end Alembic commands ###
