"""Add hospital_id to user table

Revision ID: d176237399bc
Revises: 92387ea94d1b
Create Date: 2024-11-12 13:47:29.413265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd176237399bc'
down_revision = '92387ea94d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        # Adding foreign key with a constraint name
        batch_op.create_foreign_key('fk_user_hospital', 'hospital', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Dropping the foreign key constraint by its name
        batch_op.drop_constraint('fk_user_hospital', type_='foreignkey')
        batch_op.drop_column('hospital_id')
    # ### end Alembic commands ###
